### ISSUE TITLE
Best block shows time but no date

### ISSUE THREAD

**Issue by Tbaut** [parity-js/dapp-status#2]
@UGatgithub moved from https://github.com/paritytech/parity/issues/8212 
Checking the Node information on Windows I see something like:

#5,215,466
Best block, at 01.09.22

which looks to me like there is a date missing to be displayed.

I'm running:

Which Parity version?: v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
Which operating system?: Windows
How installed?: via installer
Are you fully synchronized?: no not synced completely yet
Which network are you connected to?: Ethereum
Did you try to restart the node?: yes, I don’t think this issue is specific for my machine

**Comment by UGatgithub** [comment]
Still the same in Parity v1.10.2-20180423 beta

**Comment by UGatgithub** [comment]
1.11.4 beta still shows this issue!

**Comment by axelchalon** [comment]
![image](https://user-images.githubusercontent.com/5739676/41820862-92e856e4-77d8-11e8-8c3b-9d0cffac9b46.png)

shows up fine here!
did you update your version of [Parity UI](https://github.com/parity-js/shell) after this was fixed?

**Comment by UGatgithub** [comment]
Do I have to do that additionally to updating Parity in Windows 10?

**Comment by axelchalon** [comment]
yes, if you want the latest version of this dapp you need to update Parity UI. you don't need to update Parity for this.
